spring:
  application:
    name: multi-portfolio
  
  # Database configuration for Docker
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/portfolio}
      database: ${MONGODB_DATABASE:portfolio}
  
  # File upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# Logging configuration
logging:
  level:
    "[com.portfolio.Multi_Portfolio]": INFO
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Application specific configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: ${JWT_EXPIRATION:86400000}
  upload:
    dir: ${UPLOAD_DIR:/app/uploads/photos}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET:}
      region: ${AWS_REGION:us-east-1}
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
